---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups/finalizers
  verbs:
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - destinations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vision.middleware.io
  resources:
  - destinations/finalizers
  verbs:
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - destinations/status
  verbs:
  - get
  - patch
  - update
