apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visioncart
  namespace: odigos-system
subjects:
  - kind: ServiceAccount
    name: visioncart
    namespace: odigos-system
roleRef:
  kind: ClusterRole
  name: visioncart
  apiGroup: rbac.authorization.k8s.io
