apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: visioncart
    namespace: odigos-system
    labels:
        app: visioncart
spec:
    selector:
        matchLabels:
            app: visioncart
    template:
        metadata:
            labels:
                app: visioncart
        spec:
            serviceAccountName: visioncart
            hostNetwork: true
            hostPID: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
                - name: visioncart
                  image: ghcr.io/keyval-dev/odigos/visioncart:v0.1.37
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                  securityContext:
                      privileged: true
                  volumeMounts:
                      - name: run-dir
                        mountPath: /run
                        mountPropagation: Bidirectional
                      - name: var-dir
                        mountPath: /var
                        mountPropagation: Bidirectional
            volumes:
                - name: run-dir
                  hostPath:
                      path: /run
                - name: var-dir
                  hostPath:
                      path: /var
