---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups/finalizers
  verbs:
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - collectorsgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - instrumentedapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vision.middleware.io
  resources:
  - instrumentedapplications/finalizers
  verbs:
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - instrumentedapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vision.middleware.io
  resources:
  - odigosconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
