name: Release
on:
  push:
    tags:
      - 'v*'
      - 'middleware-test-*'
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Autoscaler Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/middleware-labs/vision-autoscaler:middleware-test-0.0.18
          build-args: SERVICE_NAME=autoscaler
          platforms: linux/amd64,linux/arm64
      # - name: Build Scheduler Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-scheduler:middleware-test-0.0.1
      #     build-args: SERVICE_NAME=scheduler
      #     platforms: linux/amd64,linux/arm64
      # - name: Build Instrumentor Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-instrumentor:middleware-test-0.0.1
      #     build-args: SERVICE_NAME=instrumentor
      #     platforms: linux/amd64,linux/arm64
      # - name: Build Detector Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: langDetector/Dockerfile
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-lang-detector:middleware-test-0.0.1
      #     build-args: SERVICE_NAME=langDetector
      #     platforms: linux/amd64,linux/arm64
      # - name: Build Odiglet Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: visioncart/Dockerfile
      #     context: visioncart/
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-odiglet:middleware-test-0.0.1
      #     platforms: linux/amd64,linux/arm64
      # - name: Build Init Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: init/Dockerfile
      #     context: init/
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-init:middleware-test-0.0.1
      #     platforms: linux/amd64,linux/arm64
      # - name: Build UI Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: ui/Dockerfile
      #     context: ui/
      #     push: true
      #     tags: ghcr.io/middleware-labs/vision-ui:middleware-test-0.0.1
      #     platforms: linux/amd64,linux/arm64
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}